# Generated by Django 4.1.6 on 2023-02-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_coord', models.FloatField(verbose_name='x')),
                ('y_coord', models.FloatField(verbose_name='y')),
                ('description', models.CharField(max_length=2000)),
                ('time_for_viewing', models.IntegerField(verbose_name='Time for viewing')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date created')),
                ('user_id', models.IntegerField(null=True)),
                ('is_static', models.BooleanField()),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_route', models.IntegerField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guide.poi')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.route')),
            ],
        ),
        migrations.CreateModel(
            name='POIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.poi')),
            ],
        ),
    ]
