# Generated by Django 4.1.6 on 2023-02-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('x_coord', models.FloatField(verbose_name='x')),
                ('y_coord', models.FloatField(verbose_name='y')),
                ('time_for_viewing', models.IntegerField(verbose_name='Time for viewing')),
            ],
        ),
        migrations.RenameModel(
            old_name='POIImage',
            new_name='PointImage',
        ),
        migrations.AlterField(
            model_name='pointimage',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.point'),
        ),
        migrations.AlterField(
            model_name='routenode',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guide.point'),
        ),
        migrations.DeleteModel(
            name='POI',
        ),
    ]
