# Generated by Django 4.1.6 on 2023-02-15 17:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_point_rename_poiimage_pointimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='date',
        ),
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 20, 51, 37, 416220), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='visited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Пройден'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='point',
            name='time_for_viewing',
            field=models.IntegerField(verbose_name='Время на осмотр'),
        ),
        migrations.AlterField(
            model_name='point',
            name='x_coord',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='point',
            name='y_coord',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
