# Generated by Django 4.1.6 on 2023-02-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_remove_route_date_route_created_route_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='time_for_viewing',
            field=models.IntegerField(default=5, verbose_name='Время на осмотр'),
        ),
        migrations.AlterField(
            model_name='route',
            name='visited',
            field=models.DateTimeField(null=True, verbose_name='Дата прохождения'),
        ),
        migrations.DeleteModel(
            name='PointImage',
        ),
    ]
