# Generated by Django 4.1.6 on 2023-02-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_point_image_alter_point_time_for_viewing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
