# Generated by Django 4.1.6 on 2023-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_point_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='is_entry_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routenode',
            name='distance_to_prev',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='route',
            name='is_static',
            field=models.BooleanField(default=True),
        ),
    ]
